### ISSUE TITLE
Blocky participating in live broadcast - no way of contacting you

### ISSUE THREAD

**Issue by GrahamCCRL** [knguy22/Blocky-Chess-Engine#236]
106TH AMATEUR SERIES (Division 10)

Waxman 2022
Shen Yu 2.0.1 64-bit
Queen 4.05 64-bit
Bienchen 1.0 64-bit
Eubos 3.3 64-bit
CeeChess 1.4 64-bit
Fatalii 0.6.0 64-bit
Cinnamon 2.5 64-bit
Motor 0.1.0 64-bit (new)
Austerlitz 1.4.7 64-bit (new)
Tcheran 2.1 64-bit (new)
Arcanum 1.12 64-bit (new)
chessplusplus 1.2.0 64-bit
Aurora 1.0.0 64-bit (new)
Simbelmyne 1.3.1 64-bit (new)
Maxwell 3.1.3 64-bit (new)
Blocky 1.0 64-bit (new)
Oxidation 0.6.0 64-bit (new)

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16069

**Comment by knguy22** [comment]
Thanks for letting me know! In the future, you can find me on the Stockfish discord with the username `intermittence`.

**Comment by GrahamCCRL** [comment]
Thanks :-)

**Comment by GrahamCCRL** [comment]
111TH AMATEUR SERIES (Division 10) AMD Ryzen 5950x ChessGUI 256mb hash each
where possible 6 piece tablebases Ponder off GBSelect2024.cgb book 12
minutes with 8 second increments. 4 cycles 52 rounds Aramis 1.4.0 64-bit
(new) Boychesser 1.0 64-bit Lozza 2.5 64-bit (relegated) Schoenemann 0.2.0
64-bit (new) Lishex 1.1.1 64-bit Illumina 1.0 64-bit (new) RookieMonster 1.9.9
64-bit Myrddin 0.90 64-bit smol.cs 1.61 64-bit (relegated) Betsabe II 2023
64-bit Blocky 2.0.0 64-bit Hedgehog 2.407 64-bit Raven 1.30 64-bit Bread 1.1.0
64-bit Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16066
